Triangle.NET added. Does not compile: Assets/Triangle/Geometry/InputGeometry.cs(83,19): error CS0266: Cannot implicitly convert type `System.Collections.Generic.List<TriangleNet.Data.Vertex>' to `System.Collections.Generic.IEnumerable<TriangleNet.Geometry.Point>'. An explicit conversion exists (are you missing a cast?)